http:
  middlewares:
    ipwhitelist-mw:
      ipAllowList:
        sourceRange:
          - "127.0.0.1/32"
          - "172.17.0.0/16"
          - "172.18.0.0/16"
          - "186.217.0.0/16"
          - "200.145.0.0/16"
          - "2801:88::/32"
